# Example configuration
jira_url = "https://example.atlassian.net"
user_login = ""
api_token = ""
# pat_token = "" # Auth for selfhosted instance
issue_query = "assignee = currentUser() ORDER BY updated DESC"
jira_timeout_seconds = 10
max_query_results = 100
enable_comment_prompts = false
one_transition_auto_move = false
inclusive_filters = true

[git_hooks]
allow_branch_missing_issue_key = false
