name: "Integration"
on:
  push:
    branches:
      - "master"
    paths:
      - "**/src/**"
      - "**/Cargo.toml"
      - .cargo/**
      - .github/workflows/integration.yml
  pull_request:
    branches:
      - master
    paths:
      - "**/src/**"
      - "**/Cargo.toml"
      - .cargo/**
      - .github/workflows/integration.yml
  workflow_dispatch:

jobs:
  test:
    name: "Cargo test"
    runs-on: [self-hosted] #, windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  lint:
    name: "Cargo check/clippy"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo check
      - run: cargo clippy -- -D warnings

  fmt:
    name: "Cargo format"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --verbose --check
