name: "Test"
on:
  push:
    branches: [ "master" ]
    paths:
      - src/**
      - .cargo/**
      - .github/**
  pull_request:
    branches: [ "master" ]
    paths:
      - src/**
      - .cargo/**
      - .github/**
  workflow_dispatch:

jobs:
  test:
    name: "Cargo test"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo test

  fmt:
    name: "Cargo format"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --verbose --check
